### ISSUE TITLE
`git`/`path` disambiguation

### ISSUE THREAD

**Issue by ysndr** [flox/runix#20]
I wondered why `/path/to/flake` was being parsed as `git+file://` by nix.
After some digging i found that nix is "pre-parsing" the flakeref url [1] where it resolves the shortcuts `flake:`, `path:` and `git+file`, constructs a new url from those and only then parses the  new url.

Notably, since `path` and `git+file` urls are somewhat overlapping (both represent a local path) nix is actually trying to resolve the flakeroot and git dir to disambiguate.

The runix impl is substituting urls as part of the parsing but does _not_ perform any io, flake resolution.

In fact, i find it a bit out of order to do io for parsing flakerefs as that would make flakeref parsing dependent on the system state its performed on.

The question is how we should handle `/path/to/flake` urls if not resolving flakes.

My approach would be to add a `FlakeRefSource` that catches parses a `PathBuf` and query as opposed to a url. It would then have an impure method to resolve to either Path or Git Flakeref.
I do wonder though whether that should be a `FlakeRef` variant or just a separate struct.

As a variant, it would likely need to fail serialization due to ambiguity!

[1] https://github.com/flox/nix/blob/master/src/libexpr/flake/flakeref.cc#L125-L186

@mkenigs note:
A bit of an optimization, we may want to pull in for a Rust sprint

**Comment by samrose** [comment]
> I do wonder though whether that should be a FlakeRef variant or just a separate struct.

What would the payoff or drawbacks be for doing it one way, or the other?

**Comment by ysndr** [comment]
Separate struct for `PathBuf`

* benefit, because `FlakeRef` would represent only unambiguous flakerefs
* benefit, isolated path-like ref handling
* drawback, awkward to parse because we have so many places wehre you naturally give just a path (CLI args)

FlakeRef variant

* benefit, easier parsing of arguments through FlakeRef
* benefit, faster to implement, does not require reimplementing nix logic now
* drawback, fallible serialization
* drawback, allows invalid flakerefs at parse time

Separate `ImpureFlakeRef`

* benefit, closer to nix
* benefit, isolated disambiguation
* benefit, can be used if and only if needed (i.e. when we cant expect unambiguous inputs)
* drawback, Another `FlakeRef` type could be confusing

**Comment by mkenigs** [comment]
> As a variant, it would likely need to fail serialization due to ambiguity!

Could we represent "this ref is unclear and we'll just pass it to Nix and let NIx figure it out"? Or would that break other logic?

Edit: oh I may have misunderstood, that's what we'd do, and we might not call the impure resolution method all the time?

**Comment by alex-ameen** [comment]
`nix prefetch --json` is an incredibly useful tool for expansion of refs
btw.

You probably already knew that but wanted to mention it just in case.

**Comment by ysndr** [comment]
well, yes we can let nix figure out flakerefs for us using:

```
nix flake metadata "ambiguous url"
```

However `nix flake metadata` will do a lot more work, i.e. fetch the flake and  **create a lockfile**, fail if there is no flake and just generally doing way more than we'd need or even want it to.
Afaik there is no `nix` command that only resolves/disambiguates a url (i.e. the internal parse method)

`nix flake prefetch` seems to be useful to get what's behind the ref but not entirely applicable here if I'm not missing something.

Also using nix at this stage is kinda mixing up abstractions.


@mkenigs what youre proposing is probably my second point, where there could be a "might be something" variant and were not resolving it at all, just passing it as argument to nix.

I tend towards option three for it being closer to nix and allowing the potential mapping to native nix values. Yet that would still "resolve" by reimplementing the nix logic (which is not _that_ severe) rather than calling out to nix.

**Comment by mkenigs** [comment]
> I tend towards option three for it being closer to nix and allowing the potential mapping to native nix values. Yet that would still "resolve" by reimplementing the nix logic (which is not _that_ severe) rather than calling out to nix.

Yeah and since we would then be giving Nix something explicit, it wouldn't have to do the work a second time

**Comment by stahnma** [comment]
Ready to merge (if done in correct order)
