### ISSUE TITLE
flakeref: Match Nix behavior for GitService `?ref=` and `?rev=`

### ISSUE THREAD

**Issue by mkenigs** [flox/runix#3]
We have a few differences at the moment:

- for `github:flox/runix/XXX`, XXX is always treated as a `rev`, when it could be a ref. Nix uses a regex match to determine which it is
- We have optional `ref` and optional `Pinned` (which contains optional `rev`), but Nix errors if a flakeref contains both `ref` and `rev`
- We serialize as `github:flox/runix?rev=XXX` but Nix serializes as `github:flox/runix/XXX`

**Comment by ysndr** [comment]
> We serialize as github:flox/runix?rev=XXX but Nix serializes as github:flox/runix/XXX

I think that one is fine those should be equivalent.


> for github:flox/runix/XXX, XXX is always treated as a rev, when it could be a ref. Nix uses a regex match to determine which it is

Eh regexes...
Can look into this, that would also need to go into your second point then.

**Comment by mkenigs** [comment]
> > We serialize as github:flox/runix?rev=XXX but Nix serializes as github:flox/runix/XXX
> 
> I think that one is fine those should be equivalent.

The problem with that is if we deserialize a catalog from update-catalog -> serialize the contents will change. Acceptable but not ideal
