### ISSUE TITLE
Nix flake update command

### ISSUE THREAD

**Issue by OliverEvans96** [flox/runix#47]
Hello,

I'm excited to use this package! However, I'd like to do `nix flake update`. It seems that `init` is the only `nix flake` subcommand currently implemented. Is that true?

Cheers,
Oliver

**Comment by mkenigs** [comment]
Hi there, glad to hear you're interested in using it!

We also have `flake metadata`, but unfortunately no `flake update` yet https://github.com/flox/runix/blob/d1ba2e30123f8cc340f22284df0c0c54dd2dd2b1/crates/runix/src/command.rs#L103

Adding a command is mostly boilerplate if you want to attempt doing it. You can look at flake init or metadata as an example. Or https://github.com/flox/runix/pull/32 is another recent PR adding a command.

**Comment by OliverEvans96** [comment]
Thanks, I'll give it a shot tomorrow.
